Dashboard
cscjam/nurse-planning pull request #16
Opened 2020-11-25 17:17 UTC by cscjam

2020-11-25 21:22 UTC, fbraure commented on app/controllers/visits_controller.rb
> +    @visit.is_done ? @visit.is_done = false : @visit.is_done = true
Je ne suis pas sur de comprendre cette ligne ? 
Update fait forcement un mark_has_done ? 
(Tu peux aussi noter @visit.is_done = !@visit.is_done

2020-11-25 21:27 UTC, fbraure requested changes

2020-11-25 21:27 UTC, fbraure commented on app/views/dashboards/show.html.erb
> +    <%= image_tag "https://thispersondoesnotexist.com/image", class: "avatar-bordered"%>
Tu peux utiliser Cloudinary :       <%= cl_image_tag current_user.avatar.key, class: "avatar bordered"%>

2020-11-25 21:27 UTC, fbraure commented on db/seeds.rb
> +    icon: "fas fa-hand-sparkles"
Il ne faut retirer les <i>. Je les utilise après. Ceux sont "i" de "icon" 
Si on les enlève, on ne pourra remplacer par une url ou un asset.

2020-11-26 07:56 UTC, CharlotteMartineau approved these changes

2020-11-26 10:29 UTC, merged