Prescription
cscjam/nurse-planning pull request #86
Opened 2021-02-09 11:11 UTC by Suricate19

Bonjour, 

Prescription Phase 1 

Création de la table Prescription 

- Une prescription appartient à un patient 
- Un patient peut avoir plusieurs prescriptions
- Une prescription peut avoir plusieurs visites
- Une visite appartient à une prescription

Création du Model - Controlleur - Vue  
Le crud fonctionne (Create - Modify - Delete - Show)
Les vues existantes et fonctionnelles 
- Prescription Index
- Prescription show 

Fonctionnalités OK 
- Prescription Index
- Prescription Create
- Prescription show 
- Créer des visites liées à une prescription
- Supprimer toutes les visites liées à une prescription

Problèmes à voir : 
-Lors de la création d'une visite liée à une prescription, le nom du patient et sa prescription ne sont pas présélectionnée dans le formulaire(important)
-Donc possibilité de crée une visite, en changeant le patient et la prescription (critique) 
-Seed, problématique pour créer plusieurs visite, le lien Patient - Prescription unique est un problème pour créer massivement des visites de tests 

Dans la phase 2, je dois avancer sur la création de visites récurrentes. 
Visites Tous les Mardi d'un patient pendant 2mois = 8 visites crées automatiquement. 

Je vais mettre à jours le Schema DB sur notre lien historique également.
Cdt
Jean-Christophe

2021-02-11 07:54 UTC, fbraure commented on app/views/prescriptions/_form.html.erb
> +  <%= f.input :end_at, label: "Date de fin", as: :string, required: false, input_html: {class: "datepicker"}%>
Si les dates ne sont pas "required", dans toutes les vues où tu les affiches, il faut tester leur présence.

2021-02-18 20:45 UTC, fbraure requested changes

2021-02-18 20:45 UTC, fbraure commented on app/controllers/prescriptions_controller.rb
> +  before_action :prescription_params, only: [:create, :update]
prescription_params ne doit pas être un before_action. 
Cela définit les paramètres autorisés
Tu peux supprimer cette ligne

2021-02-18 20:45 UTC, fbraure commented on app/controllers/prescriptions_controller.rb
> +    @results = (@prescription.start_at..@prescription.end_at).to_a.select { |k| @my_days.include?(k.wday) }
Tant que tu n'as pas les CheckBox tu peux mettre 
@my_days = []
if @prescription.schedule.upcase.includes("LUNDI") 
  @my_days << 1
end
if ... MARDI
...

2021-02-18 20:45 UTC, fbraure commented on app/controllers/visits_controller.rb
>      @last_visit_done = @current_patient.visits.where(is_done: true).last
Il vaut mieux que tu gardes sur @visit.patient mais dans le model Visit.rb ajoute
  has_one :patient, through: :prescription
Comme cela, si tu oublies quelques part un visit.patient, tu ne casses rien

2021-02-18 20:45 UTC, fbraure commented on app/controllers/visits_controller.rb
> +    @current_prescription = Prescription.find(params[:prescription_id])
Je ne sais pas encore où tu utilises @current_prescription, mais il est surprenant que tu ais cette affectation ici, alors que ligne 82 tu testes la présence de prescription_id

2021-02-18 20:45 UTC, fbraure commented on app/controllers/visits_controller.rb
> +    @current_patient = @current_prescription.patient
Du coup, il n'y a pas de prescription_id, cette ligne va planter. 
Ces deux lignes (76 et 77) ne sont pas nécessaires avec les tests ci-dessous.

2021-02-18 20:45 UTC, fbraure commented on app/controllers/visits_controller.rb
> +    if params[:prescription_id].present?
il est préférable de mettre ce if après celui-ci qui est dessous. Et tu pourras affecter @visit.patient

2021-02-18 20:45 UTC, fbraure commented on app/models/journey.rb
>        get_each_journey_infos(points, locomotion)
Reste sur p.patient après avoir mis les has_one through

2021-02-18 20:45 UTC, fbraure commented on app/models/visit.rb
> +  has_many :patients, through: :prescriptions
has_one :patient, through: :prescription

2021-02-18 20:45 UTC, fbraure commented on app/views/dashboards/show.html.erb
>                  <p>RDV : <strong><%=visit.get_wish_time%></strong></p>
visit.patient à conserver

2021-02-18 20:45 UTC, fbraure commented on app/views/prescriptions/_form.html.erb
>    <%= f.association :patient, label_method: :get_full_name, value_method: :id, include_blank: false%>
normalement false est la valeur par défaut de required. Tu n'as pas besoin de mettre required: false.
On ajoute required pour spécifier true plutôt.

2021-02-19 09:47 UTC, Suricate19 commented on app/controllers/prescriptions_controller.rb
> +  before_action :prescription_params, only: [:create, :update]
Done sur ma branche, visible sur le prochain commit

2021-02-19 09:48 UTC, Suricate19 commented on app/controllers/prescriptions_controller.rb
> +    @results = (@prescription.start_at..@prescription.end_at).to_a.select { |k| @my_days.include?(k.wday) }
Smart ! 
Je m'attele aux checkbox dès aujourd'hui. Mais je conserve cela en tête. 

Merci

2021-02-19 09:50 UTC, Suricate19 commented on app/controllers/visits_controller.rb
>      @last_visit_done = @current_patient.visits.where(is_done: true).last
Sur ce point, j'avais déjà 
has_many :patients, through: :prescription
ce qui n'était pas parfaitement exact, mais qui aurait du permettre un visit.patient... 
Mais ce n'était pas le cas.

2021-02-19 16:35 UTC, fbraure commented on app/controllers/prescriptions_controller.rb
>    def create
Les variables avec "@" servent à envoyer de la donné du controleur à la vue. 
Après un Créate, tu vas soit dans ta prescription.show soit dans le new si il ya une erreur de validation.
Dans ces deux cas, @results et @days ne sont pas transmis. Il faut donc que tu enlèves les "@" pour éviter la confusion.

2021-02-19 16:35 UTC, fbraure commented on app/controllers/prescriptions_controller.rb
> +    if @prescription.lundi == true
est équivalent à   if @prescription.lundi

2021-02-19 16:35 UTC, fbraure commented on app/controllers/prescriptions_controller.rb
>    end
Pour le principe...
Je note que ce n'est pas trés anglosaxon... "Lundi"...

2021-02-19 16:35 UTC, fbraure commented on app/views/prescriptions/index.html.erb
> +              <p>Récurrence : <%= @schedule %></p>
Cela devrait rester prescription.Schedule. 
Le premier jet était bien

2021-02-19 16:35 UTC, fbraure commented on app/views/prescriptions/show.html.erb
> +    <p>Schedule : <%= @schedule %> </p>
@prescription.schedule

2021-02-19 16:35 UTC, fbraure commented on app/views/visits/show.html.erb
> +    <a href="tel:<%= @visit.patient.phone %>"><i class="fas fa-mobile-alt mt-1"></i> <%= @visit.prescription.patient.phone %></a>
Un ".prescription" oublié sur le dernier morceau

2021-02-19 16:43 UTC, Suricate19 commented on app/controllers/prescriptions_controller.rb
> +    if @prescription.lundi == true
Bien vu la petite refacto :P

2021-02-19 16:44 UTC, Suricate19 commented on app/controllers/prescriptions_controller.rb
>    end
Oui tu as raison, c'est pas beau, je ferais une migration là dessus.

2021-02-19 16:45 UTC, Suricate19 commented on app/views/prescriptions/index.html.erb
> +              <p>Récurrence : <%= @schedule %></p>
le champs schedule n'existe plus dans la DB, remplacé par les jours de la semaine. 
J'ai donc une variable d'instance dans laquelle je pousse les jours, pour l'affichage. 
Il y a certainement une refacto possible là dessus. 
Mais j'aimerai voir avc toi les refacto

2021-02-19 16:50 UTC, fbraure commented on app/views/prescriptions/index.html.erb
> +              <p>Récurrence : <%= @schedule %></p>
Ok, j'avais mal vu, dans ce cas, laisse @schedule, mais avant les if-if-if-if... ajoute un commentaire 
#TODO refacto: migrer en Decorator
Je te montrerai ça.

2021-02-22 14:55 UTC, Suricate19 commented on app/views/prescriptions/_form.html.erb
> +  <%= f.input :end_at, label: "Date de fin", as: :string, required: false, input_html: {class: "datepicker"}%>
Ok modifié

2021-02-22 15:05 UTC, Suricate19 commented on app/controllers/visits_controller.rb
> +    @current_patient = @current_prescription.patient
J'ai enfin compris ta remarque, et j'ai fait des modifs dans la PR du jour.

2021-02-22 15:12 UTC, Suricate19 commented on app/models/journey.rb
>        get_each_journey_infos(points, locomotion)
Fait dans la PR du jour

2021-02-22 15:24 UTC, Suricate19 commented on app/controllers/prescriptions_controller.rb
>    def create
Je comprends le point. 

Toutefois, j'avais besoin de variable d'instance pour le front. 
J'ai supprimé sur Results et Days, car c'était pour mon debeug lors du developpement et les afficher dans la console. 

Toutefois, j'ai besoin du @schedule maintenant pour afficher les jours de la semaine selectionnés.

2021-02-22 15:25 UTC, Suricate19 commented on app/views/prescriptions/show.html.erb
> +    <p>Schedule : <%= @schedule %> </p>
Le champs Schedule n'existe plus en base. 
Il s'agit d'un champs calculé ici dans ma methode de Show en fct des jours de la semaine qui sont cochés.

2021-02-23 18:12 UTC, merged